"""add platform fields

Revision ID: 90edde7f4089
Revises: a699c588bfed
Create Date: 2026-02-15 06:37:28.778744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90edde7f4089'
down_revision: Union[str, Sequence[str], None] = 'a699c588bfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('platform', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_platform'), 'messages', ['platform'], unique=False)
    op.add_column('sessions', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sessions_external_id'), 'sessions', ['external_id'], unique=False)
    op.create_index(op.f('ix_sessions_platform'), 'sessions', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_platform'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_external_id'), table_name='sessions')
    op.drop_column('sessions', 'external_id')
    op.drop_column('sessions', 'platform')
    op.drop_index(op.f('ix_messages_platform'), table_name='messages')
    op.drop_column('messages', 'platform')
    # ### end Alembic commands ###
