"""add proactive fields to sessions

Revision ID: 9fec7f3eabb3
Revises: b865210c7022
Create Date: 2026-02-14 09:45:45.956735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fec7f3eabb3'
down_revision: Union[str, Sequence[str], None] = 'b865210c7022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('proactive_enabled', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('silence_threshold_min', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('silence_cooldown_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'silence_cooldown_min')
    op.drop_column('sessions', 'silence_threshold_min')
    op.drop_column('sessions', 'proactive_enabled')
    # ### end Alembic commands ###
