"""add user_turn to messages

Revision ID: a699c588bfed
Revises: 9fec7f3eabb3
Create Date: 2026-02-14 12:09:13.204722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a699c588bfed'
down_revision: Union[str, Sequence[str], None] = '9fec7f3eabb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_turn', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_user_turn'), 'messages', ['user_turn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_turn'), table_name='messages')
    op.drop_column('messages', 'user_turn')
    # ### end Alembic commands ###
